version: "3" # Especifica a versão do docker-compose

services: # Define um serviço
  app: # Nome do serviço
    build: . # Local do arquivo Dockerfile
    image: nlw/ecoleta:1.0 # Nesse cenário, a imagem construida a partir do build, irá ficar no repositorio/tag local nlw/ecoleta
    # Expoe a porta que o container vai receber comunicação.
    expose:
      - "3000"
      
  loadbalancer: #Load Balancer
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: # Informa que esse serviço depende do serviço app para poder ser executado
      - app
    ports:
      - "8000:8080"
