version: "3" # Especifica a versão do docker-compose

services: # Define um serviço
  app: # Nome do serviço
    build: . # Local do arquivo Dockerfile
    image: nlw/ecoleta:1.0 # Nesse cenário, a imagem construida a partir do build, irá ficar no repositorio/tag local nlw/ecoleta
    command: npm start # Comando a executar quando o container for iniciado
    ports:
      - "3000:3000" # Redirecionamento de porta entre a máquina local e o container. Ex.: Quando a requisição chegar na máquina local na porta 3000 ela será redirecionada para a porta 3000 do container.
    volumes:
      - .:/usr/app # Volume a ser compartilhado entre a máquina local e o container. Ex.: Quando algum arquivo for alterado na pasta local, irá também ser alterado no container na pasta /usr/app.
