apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  name: {{ include "keycloak-operator.fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "keycloak-operator.selectorLabels" . | nindent 4}}
  type: ClusterIP