{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-operator.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "keycloak-operator.serviceAccountName" . }}
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}