name: Publish Docker image

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and update manifest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker tag
        id: generate_tag
        run: |
          TAG="${GITHUB_REF##*/}"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            IMAGE_TAG="luancarlos021/ecoleta:${TAG}"
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            IMAGE_TAG="luancarlos021/ecoleta:dev-${SHORT_SHA}"
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.generate_tag.outputs.IMAGE_TAG }}

      - name: Update image tag in Kubernetes manifest
        run: |
          ESCAPED_TAG=$(echo "${{ steps.generate_tag.outputs.IMAGE_TAG }}" | sed 's_/_\\/_g')
          sed -i "s|luancarlos021/ecoleta:.*|${ESCAPED_TAG}|" ops/e-coleta/e-coleta-app.yaml

      - name: Commit updated manifest
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ops/e-coleta/e-coleta-app.yaml
          git commit -m "chore: update image tag to ${{ steps.generate_tag.outputs.IMAGE_TAG }}"
          git push
