name: Publish Docker image

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        id: login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: luancarlos021/ecoleta
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: luancarlos021/ecoleta:v1.1.${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Kubernetes manifest image tag
        run: |
          sed -i "s|luancarlos021/ecoleta:.*|luancarlos021/ecoleta:v1.1.${{ github.run_number }}|" ops/e-coleta/e-coleta-app.yaml
          
      - name: Commit updated manifest
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ops/e-coleta/e-coleta-app.yaml
          git commit -m "chore: update image tag to v1.1.${{ github.run_number }}"
          git push
