name: Docker Build Deploy
on:
  push:
    branches: [master] 
  workflow_dispatch:
env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  PRODUCT_REPO_NAME: ${{secrets.PRODUCT_REPO_NAME}}
jobs:
  create-user-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v2
      
      - name: Work Dir
        run: |
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $PRODUCT_REPO_NAME
          
      - name: Docker login
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          
      - name: Build user service docker image
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          run: docker build . --file Dockerfile -t "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:v1.0.${{ github.run_number }}"
        
      - name: Push user service docker image
        run: docker push "$DOCKER_USERNAME/$PRODUCT_REPO_NAME:v1.0.${{ github.run_number }}"
